// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.

var firstTerm = 1,
    secondTerm = 2,
    thirdTerm = 0,
    result = 2;

while(thirdTerm < 4000000) {
  thirdTerm = firstTerm + secondTerm;
  firstTerm = secondTerm; // reassigns variables
  secondTerm = thirdTerm; // reassigns variables
  if(thirdTerm % 2 === 0) { // if even, add to result
    result = thirdTerm + result;
    console.log(result);
  }
}
