// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.

var first_term = 1,
    second_term = 2,
    third_term = 0,
    result = 2;

while(third_term < 4000000) {
  third_term = first_term + second_term;
  first_term = second_term; // reassigns variables
  second_term = third_term; // reassigns variables
  if(third_term % 2 === 0) { // if even, add to result
    result = third_term + result;
  }
}
